name: "units-test"
on:
  # Triggers the workflow on push
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test

  # test action works running from the graph
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Load environment variables
        uses: artursouza/export-env-action@v2
        with:
          envFile: "./.github/env/global.env"
          expand: "true"
      # Test that the default version is used
      - name: Setup Dapr CLI default version
        uses: ./
        if: ${{ matrix.os == 'windows-latest'}}
      # Test that explicit version is used
      - name: Setup Dapr CLI specific version
        uses: ./
        if: ${{ matrix.os != 'windows-latest'}}
        with:
          version: ${{ env.DAPR_CLI_VERSION }}
      - name: Initialize Dapr
        if: ${{ matrix.os == 'ubuntu-latest'}}
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          dapr init --runtime-version=${{ env.DAPR_RUNTIME_VERSION }}
          dapr --version
